### ISSUE TITLE
New iOS update to 6.1 causes petal animation fail

### ISSUE THREAD

**Issue by 0xjmp** [KieranLafferty/KLExpandingSelect#3]
As I'm sure you've just updated your device, if you run the petal animation, it fails horribly :(

**Comment by 0xjmp** [comment]
More specifically, a quarterSpinningBlock() warning occurs that states that the declaration of the function could lead to a retain cycle.

**Comment by 0xjmp** [comment]
If you haven't fixed this issue already, I have fixed it. Let me know if you're interested, and I'll do a pull request.

**Comment by KieranLafferty** [comment]
Hey @jsksma2 thanks for making a fix, create a pull request and I will merge it

**Comment by anthonycastelli** [comment]
Has this issue been fixed yet? Im still receiving the same issue

**Comment by 0xjmp** [comment]
No, I never ended up getting around to it

On Sunday, April 7, 2013, anthonycastelli wrote:

> Has this issue been fixed yet? Im still receiving the same issue
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KieranLafferty/KLExpandingSelect/issues/3#issuecomment-16025777
> .

## 

Jake Peterson
951.333.2642
Jsksma2@gmail.com
www.jakepthats.me

**Comment by anthonycastelli** [comment]
How did you end up fixing the issue. Its the only warning in my project and driving me nuts haha

**Comment by 0xjmp** [comment]
I would try re-writing the block so you can set a weak self. You can do
that using: __weak __typeof(self)weakSelf = self;

On Monday, April 8, 2013, anthonycastelli wrote:

> How did you end up fixing the issue. Its the only warning in my project
> and driving me nuts haha
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KieranLafferty/KLExpandingSelect/issues/3#issuecomment-16082961
> .

## 

Jake Peterson
951.333.2642
Jsksma2@gmail.com
www.jakepthats.me

**Comment by anthonycastelli** [comment]
I've tried that, I end up with a  warning on self.transform. Will play with it some more.

**Comment by KieranLafferty** [comment]
Hey all, I fixed this issue by performing a recursive function instead of using blocks enjoy!

**Comment by KieranLafferty** [comment]
See the latest commit for code
